nodeLinker: pnp

packageExtensions:
  "@wagmi/core@*":
    peerDependencies:
      "@tanstack/query-core": "*"
  "@wagmi/connectors@*":
    peerDependencies:
      "@tanstack/query-core": "*"
  "wagmi@*":
    peerDependencies:
      "@tanstack/query-core": "*"
  "eslint-config-next@*":
    peerDependencies:
      "next": "*"
