[profile.default]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 10_000
evm_version = "paris"
fs_permissions = [{ access = "read-write", path = "./"}]

# Répertoires
src = "src"
test = "test"
script = "script"
